# -*- coding: utf-8 -*-
"""atividade03-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWklkYNXGtqY0_8Z99ObL7oQ9EW05jMR
"""

import pandas as pd
import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

NHE = pd.read_excel('/content/ex-1.xlsx')

NHE.describe()

CV = (2.53 / 18.41) * 100
print(CV)

NHE2 = pd.read_excel('/content/ex-2.xlsx')

NHE2.describe()

CV2 = (1.21 / 1.95) * 100
print(CV2)

NHE3 = pd.read_excel('/content/ex-3.xlsx')

NHE3.describe()

CV3 = (3.64 / 6.50) * 100
print(CV3)